export const types = Object.freeze({
  FILMS_START_FETCHING: 'FILMS_START_FETCHING',
  FILMS_STOP_FETCHING: 'FILMS_STOP_FETCHING',
  FILMS_FILL: 'FILMS_FILL',
  FILMS_SET_FETCHING_ERROR: 'FILMS_SET_FETCHING_ERROR',
  FILMS_FETCH_ASYNC: 'FILMS_FETCH_ASYNC',

  FILM_FILL: 'FILM_FILL',
  FILM_FETCH_ASYNC: 'FILM_FETCH_ASYNC',
});